xcp-ng/uefistored

Makefile
README.md
tests/Makefile

Trying to compile munit 2.0 with gcc version 4.8.5 (as found our build environment for Koji) results in a complaint about c99, yet 2.0 is the only available public archive of the project.  This adds the -std=c99 tag for building munit and so enables our munit tests to be built and then ran in the Koji environment.
It also changes the archive make target to use gzip instead of xz (although this is not used in our RPM).
It also adds a small README fix.

Support munit 2.0 with gcc version 4.8.5, change to gzip for archive, fixup README

---

CHANGELOG.md
scripts/secureboot-certs

@stormi Are you okay with the version bump to v1.0.0?
Following semantic versioning, the `secureboot-certs` changes break the previous "API" which is the CLI, so deserve a MAJOR version bump.

Support cert sync via XAPI with secureboot-certs

---

CHANGELOG.md
src/uefi/authlib.c

By preventing the PK loading when there is no KEK/db we avoid situations
where dbx updates are being rejected purely because SecureBoot==1
(because the PK is loaded) and there is no KEK.

fix: windows KB error

---

scripts/secureboot-certs

Previously, secureboot certs would derive the cert name from the filename of the cert, so "mycert.auth" passed in as a "PK" cert would result in a cert called "mycert" not "PK".  This PR fixes that and makes a few cosmetic improvements too.

Fix secureboot certs

---

CHANGELOG.md
Common.mk
Makefile
README.md
inc/log.h
inc/uefi/pkcs7_verify.h
src/log.c
src/uefi/auth.c
src/uefi/authlib.c
src/uefi/pkcs7_verify.c
src/uefistored.c
tests/Makefile
tests/conf/test.conf
tests/test.c

This PR adds the ability to print out the failed certificates if an authenticated variable cert failure occurs.  Because certificates contain a good amount of information, and in order to avoid polluting the logs, this is only done if the log level is set to DEBUG.  Because the log level was previously compiled in, this is not easy to change conveniently on a running system.  Therefore, this PR also adds support for a small configuration file located at `/etc/uefistored/uefistored.conf` that contains just one option: `loglevel`.
The config file looks like this:
```
loglevel=DEBUG
```
Other values for loglevel may be `ERROR`, `INFO`, or `WARNING`.  If the file or its directory are missing, then the log level will default to `INFO` (the level used in previous uefistored versions).  If the …

Print cert failure and add configurable debug level

---

scripts/secureboot-certs

The python-requests package is not installed by default in dom0.
Instead of requiring it as a dependency, this commit uses of Python's
standard urllib2, which should not add any further dependencies.
urllib2 is a little less ergonomic as the downloads in secureboot-certs
fails if certain headers are not defined (unlike the requests library,
which sets them itself).  The rationale behind those headers is
commented inline.

fix(secureboot-certs): remove python-requests dependency

---

inc/variable.h
tests/Makefile

Compiling the tests with GCC11 with flag -Werror fails due to two
violations.  One is -Warray-parameter and the other is -Wvla-parameter.
This commit fixes the code violating the array-parameter check.  It
suppresses the vla-parameter check when building tests because the
violating code exists in the munit dependency, not in uefistored itself.
Some future vla-parameter violations may wrongfully suppressed as a side
effect when building the tests.  The production build will not have that
error suppressed.

build: fix new GCC 11 warnings

---

src/uefi/pkcs7_verify.c

In order for OpenSSL errors to be printed reliably, the crypto
strings must be loaded prior to the print.
This commit moves the string loading prior to printing the errors.

fix(pkcs7): print OpenSSL errors when PKCS7 verify fails

---

CHANGELOG.md
src/uefistored.c

To give users the option of changing the PK.auth but still protect the
default PK, let uefistored open the PK from /var/lib/uefistored.
According to the FHS, files in /usr/share/ should not be modified by
users.

fix: /usr/share/uefistored/PK.auth -> /var/lib/uefistored/PK.auth

---

scripts/secureboot-certs

To help reduce the amount of typing required for the common case, this
commit invokes all of the default and latest certificates if no args are
passed to the install command

feat(secureboot-certs): force default options when no install arguments are passed

---

scripts/secureboot-certs

This commit fixes the broken pipe error that happens when piping
the report output into less and then quitting less before
reaching EOF.

fix(secureboot-certs): broken pipe error

---

scripts/secureboot-certs

This PR adds format checking of the input files for custom certs.
It also adds which formats are required for which file:
PK: EFI auth file
KEK: X509 DER
db: X509 DER
dbx: EFI auth file

feat(secureboot-certs): check format of input files

---

Makefile

Due to changes in commit d4f9d17bdd9c0284817ca3b43775a5c2f126d904,
the $(@D) and $(@F) special variables are only evaluated once, rather
than for each target.
This commit changes the assignment operator for CFLAGS back to = instead
of :=.

Fix build on uefistored 1.1.0

---

scripts/secureboot-certs

The previous messages were confusing about what the program wants from
the user. This commit clearly states why the input was wrong and what
is expected.

feat(secureboot-certs): make format errors unambiguous

---

scripts/secureboot-certs

This commit adds support for secureboot-certs to accept any of the
following formats as input files:
- EFI auth
- DER-encoded X509
- PEM-encoded X509
secureboot-certs internally converts all of these file formats into an
auth file.  Besides making life easier for users, this also allows users
to put multiple certificates together into a single auth file and pass
in that auth file to secureboot-certs.
This commit does NOT support passing in multiple PEM/DER encoded X509
certificates for a single UEFI variable. If a user wishes to do this,
they must use a tool like `create-auth` or `efitools` to bundle the X509
certificates into a single EFI auth file and pass that to
secureboot-certs.
This was tested using the following files (existing internally in on Vates Env B machine 22):
``` …
```

Secureboot certs uniform args

---

scripts/secureboot-certs

This commit supports extracting certificates from the XAPI DB using the
command `secureboot-certs extract <CERT> <filename>`. It may be of use
to users, but will definitely be of use in testing. It allows tests to
save/restore certs before/after modifying them for tests.

secureboot-certs: add extract command

---

src/log.c
src/uefi/authlib.c
src/uefistored.c

This commit either reduces overzealous ERROR() messages to WARNING()
messages. If the message occurs during normal operation of a VM (such as
uefistored receiving an IO event that it doesn't know how to handle),
then the message is removed altogether.
Finally, a newline char was added to a message that was missing one.

logging: demote or remove superfluous error messages

---

src/uefistored.c

Port of https://github.com/xapi-project/varstored/commit/f8c2656be1cfca35bb9297b97d9af962f51f19f9 :
> This logically reverts c/s https://github.com/xapi-project/varstored/commit/1a4bc4fbdd5bed4ad26aec24aa1a75374f34e152 "CA-294027: Wait for ioreq server pages
> to become available".
> The workaround was made obsolete by c/s https://github.com/xapi-project/varstored/commit/f00b12dc1d0c6e1e0574a3dc8db59a66eb533fa2 "CA-322067: Use new
> resource mapping API".
> Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>

Don't wait for ioreq server frames to appear

---

src/uefistored.c

Port of https://github.com/xapi-project/varstored/commit/7c7025e1adab52db51320f2ffc224b9f638c626c :
> evtchn port 0 is never valid.  Use calloc() instead of malloc().
> Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>
For uefistored code, the only change is to use `calloc` instead of `malloc`

Don't use -1 for unallocated evtchn ports

---

src/uefistored.c

For now, when a VM is started with SB enabled, the log says without SB.
Original commit from Andrei Semenov <andrei.semenov@vates.fr>:
- https://github.com/xcp-ng/uefistored/pull/41/commits/c16e290c1ca56ddd86d75b7912d7c8dd5e404aee
Co-authored-by: Andrei Semenov <andrei.semenov@vates.fr>

Report correct boot mode for started VM

---

scripts/secureboot-certs

See: https://github.com/xapi-project/xen-api/pull/4659
`Host` API is deprecated in favor of `Pool` API

Update secureboot-certs for new UEFI certificates API

---

scripts/secureboot-certs

- `--user-agent=...` and `--user-agent ...` can be used
- If none is provided, use by default: 'Mozilla/5.0 - Open source hypervisor'

Add an option to set user-agent for MS certs download
